# Generated by Django 6.0 on 2025-12-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='temp_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='workflow_stage',
            field=models.CharField(default='greeting', max_length=50),
        ),
    ]
