# Generated by Django 6.0 on 2025-12-07 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_chatsession_temp_data_chatsession_workflow_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'verbose_name': 'Chat Session', 'verbose_name_plural': 'Chat Sessions'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Loan Application', 'verbose_name_plural': 'Loan Applications'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='is_existing',
            new_name='pan_verified',
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='created_at',
            new_name='applied_at',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='conversation_history',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='current_agent',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='loan_application',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='temp_data',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='workflow_stage',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='conversation_data',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='stage',
            field=models.CharField(choices=[('greeting', 'Greeting'), ('name_collection', 'Name Collection'), ('pan_verification', 'PAN Verification'), ('loan_details', 'Loan Details'), ('salary_verification', 'Salary Verification'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='greeting', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_card_image',
            field=models.FileField(blank=True, null=True, upload_to='pan_cards/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_verification_confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='approval_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='assessment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='salary_slip',
            field=models.FileField(blank=True, null=True, upload_to='salary_slips/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pan',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='base.customer'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='purpose',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='chatsession',
            table='chat_sessions',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='loanapplication',
            table='loan_applications',
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('pan_card', 'PAN Card'), ('aadhar_card', 'Aadhar Card'), ('salary_slip', 'Salary Slip')], max_length=20)),
                ('document_file', models.FileField(upload_to='verifications/')),
                ('is_verified', models.BooleanField(default=False)),
                ('confidence_score', models.IntegerField(blank=True, null=True)),
                ('extracted_data', models.JSONField(default=dict)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('ai_model_used', models.CharField(default='gpt-4o', max_length=100)),
                ('verification_timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='base.customer')),
            ],
            options={
                'verbose_name': 'Document Verification',
                'verbose_name_plural': 'Document Verifications',
                'db_table': 'document_verifications',
                'ordering': ['-verification_timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='SalarySlip',
        ),
    ]
