# Generated by Django 6.0 on 2025-12-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_chatsession_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='stage',
            field=models.CharField(choices=[('greeting', 'Greeting'), ('name_collection', 'Name Collection'), ('pan_collection', 'PAN Collection'), ('pan_verification', 'PAN Verification'), ('loan_details', 'Loan Details'), ('salary_verification', 'Salary Verification'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='greeting', max_length=50),
        ),
    ]
