# Generated by Django 6.0 on 2025-12-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_chatsession_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='face_match_confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='face_match_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='selfie_image',
            field=models.FileField(blank=True, null=True, upload_to='selfies/'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='stage',
            field=models.CharField(choices=[('greeting', 'Greeting'), ('name_collection', 'Name Collection'), ('pan_collection', 'PAN Collection'), ('pan_verification', 'PAN Verification'), ('selfie_verification', 'Selfie Verification'), ('loan_details', 'Loan Details'), ('salary_verification', 'Salary Verification'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='greeting', max_length=50),
        ),
    ]
