# Generated by Django 6.0 on 2025-12-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customer_face_match_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='temp_dob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_segment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('salaried', 'Salaried'), ('self_employed', 'Self Employed'), ('business_owner', 'Business Owner'), ('freelancer', 'Freelancer'), ('gig_worker', 'Gig Worker'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='segment_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='bank_statements',
            field=models.FileField(blank=True, null=True, upload_to='bank_statements/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='credit_score_threshold_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='customer_segment_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='emi_ratio_threshold_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='gst_document',
            field=models.FileField(blank=True, null=True, upload_to='gst_documents/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='itr_document',
            field=models.FileField(blank=True, null=True, upload_to='itr_documents/'),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='document_type',
            field=models.CharField(choices=[('pan_card', 'PAN Card'), ('aadhar_card', 'Aadhar Card'), ('salary_slip', 'Salary Slip'), ('selfie', 'Selfie'), ('itr', 'ITR Document'), ('gst', 'GST Document'), ('bank_statement', 'Bank Statement')], max_length=20),
        ),
    ]
