# Generated by Django 5.2.7 on 2025-12-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_chatsession_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='temp_pan_image_data',
            field=models.TextField(blank=True, help_text='Temporary base64 encoded PAN image for face matching - cleared after verification', null=True),
        ),
    ]
