# Generated by Django 5.2.7 on 2025-12-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_chatsession_temp_pan_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='salary_slip_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='sanction_letter_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
