# Generated by Django 5.2.7 on 2025-12-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_loanapplication_salary_slip_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='designation',
            field=models.CharField(blank=True, help_text='Job title/position (e.g., Senior Software Engineer, Manager)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='employment_duration_months',
            field=models.IntegerField(blank=True, help_text='Duration with current employer in months', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='existing_obligations',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total monthly EMI of existing loans', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='score_category',
            field=models.CharField(blank=True, help_text='Excellent/Good/Fair/Poor', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='selfie_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='credit_score',
            field=models.IntegerField(blank=True, help_text='Credit score calculated at time of application', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='max_eligible_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum loan amount customer is eligible for', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='score_breakdown',
            field=models.JSONField(blank=True, help_text='Detailed breakdown of credit score calculation', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_score',
            field=models.IntegerField(default=0, help_text='Dynamically calculated credit score (300-900)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('salaried', 'Salaried'), ('self_employed', 'Self Employed'), ('business_owner', 'Business Owner'), ('freelancer', 'Freelancer'), ('gig_worker', 'Gig Worker'), ('government', 'Government'), ('contract', 'Contract'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pre_approved_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dynamically calculated maximum loan amount', max_digits=10),
        ),
    ]
